<a href="https://colab.research.google.com/github/AnjChavan22/-Intelligent-Mobile-Addiction-Level-Prediction/blob/main/SectionA_%3CAnjali_Ajay_Chavan%3E_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unlox Python Programming Assignment

**Name:** ANJALI CHAVAN

**Roll No:**   

**Batch:** June 2026

**Subject:** Data Science

# Week 1 — Master Assignment
## Python Fundamentals + NumPy Foundations


## Section A — Theory (Interview Focus)

### Q1. `is` vs `==`

- `==` operator checks if two variables have the **same value**, while `is` operator checks if they point to the **same object in memory**.

- Two variables can be `==` (same value) but `is` returns False because Python created two separate list objects.

**Example:**
```python
a = [1, 2, 3]
b = [1, 2, 3]
print(a == b)  # True  — values are equal
print(a is b)  # False — different objects in memory
```


### Q2. Mutable vs Immutable

| Type | Mutable? |
|------|----------|
| list | ✅ Mutable |
| tuple | ❌ Immutable |
| set | ✅ Mutable |
| dict | ✅ Mutable |
| str | ❌ Immutable |
| int | ❌ Immutable |
| float | ❌ Immutable |
| bool | ❌ Immutable |
| frozenset | ❌ Immutable |

**Why immutability matters:**

 - Immutable objects cannot be changed after creation, which helps avoid unintended modifications. Since they are hashable, they can be used as keys in dictionaries and elements in sets.


### Q3. `print(0.1 + 0.2 == 0.3)` — Output and Explanation

**Output: `False`**

- At first glance, we might expect the result to be True because 0.1 + 0.2 = 0.3 mathematically. However, computers store decimal numbers in binary format, and values like 0.1 and 0.2 cannot be represented exactly. As a result, when they are added together, the actual stored value becomes slightly different from 0.3.



### Q4. Three Situations Where a Tuple is Preferred Over a List

1. **Storing fixed data** — Tuples are useful when the data should not change after it is created. For example, a database configuration containing a host name, port number, and database name can be stored in a tuple to prevent accidental changes.

2. **Dictionary keys** — Since tuples are immutable, they can be used as keys in a dictionary. For example, a pair of coordinates (latitude, longitude) can be used as a key to store or retrieve location information. Lists cannot be used as dictionary keys because they are mutable.

3. **Returning multiple values from a function** — When a function needs to return more than one value, Python automatically groups them into a tuple. This makes it easy to return related values together while indicating that the returned data is a fixed set of results.

###Q5. Why Dictionary Lookup is O(1) but List Lookup is O(n)

**Example:** Imagine a college student database.

- **In a dictionary**, you can find a student's details directly using their roll number:

```python
students = {101: "Anjali", 102: "Rahul", 103: "Priya"}
```
Looking up roll number 102 is very fast because Python uses hashing to jump directly to the correct record (O(1)).

- **In a list**, you would need to check each student's roll number one by one until you find 102:
```python
students = [101, 102, 103]
```
This may require scanning multiple elements (O(n)).

- Therefore, dictionaries provide faster lookups because they use hashing, while lists require sequential searching.

### Q6. `range()` vs `numpy.arange()`

| Feature | `range()` | `numpy.arange()` |
|---|---|---|
| Return type | `range` object (lazy) | NumPy ndarray (in memory) |
| Float support | ❌ Only integers | ✅ Supports floats e.g. `np.arange(0, 1, 0.1)` |
| Memory | Very memory-efficient (stores only start/stop/step) | Stores all values in memory |
| Operations | No vectorized math | Supports broadcasting, slicing, math ops |

**Float example:** `range(0, 1, 0.1)` raises -> `TypeError`. `np.arange(0, 1, 0.1)` -> useful when working with floating-point values.

### Q7. `append` vs `extend` vs `insert`

```python
a = [1, 2, 3]
x = [4, 5]
```

- `append(x)` adds the entire list as a single element at the end.

```python
a.append(x)
# [1, 2, 3, [4, 5]]
```
- `extend(x)` adds each element of x separately to the list.

```python
a.extend(x)
# [1, 2, 3, 4, 5]
```
- insert(i, x) inserts the entire list as a single element at a specified position.

```python
a.insert(1, x)
# [1, [4, 5], 2, 3]
```
In simple words:

- append() → adds one item at the end.
- extend() → adds multiple items from another iterable.
- insert() → adds one item at a specific position.

### Q8. Extended Unpacking with `*`
Examples:
```python
a, *b, c = [10, 20, 30, 40, 50]
# a = 10, b = [20, 30, 40], c = 50
```
The * operator is used to collect the remaining values into a list. Here, a gets the first value, c gets the last value, and b stores all the values in between.

Examples:
```python
a, *b, c = [10, 20]
# a = 10, b = [], c = 20
```
Since there are no values between the first and last elements, b becomes an empty list.
```python
a, *b, c = [10]
```
This gives a ValueError because at least two values are required—one for a and one for c.

- In simple words: *b acts like a collector that gathers all the extra values between the other variables into a list.

### Q9. `/`, `//`, `%`, `**` — Applied to (-7, 2)

| Operator | Purpose | Result for (-7, 2) |
|---|---|---|
| `/` | True division | `-3.5` |
| `//` | Floor division| `-4` |
| `%` | Remainder( Modulo ) | `1` |
| `**` |Power | `49` (-7 raised to power 2) |

Explanation:

- -7 / 2 = -3.5 gives the exact division result.
- -7 // 2 = -4 because floor division rounds down to the nearest smaller integer.
- -7 % 2 = 1 because (-4 × 2) + 1 = -7.
- (-7) ** 2 = 49 because -7 × -7 = 49

**Note:**
For negative numbers, floor division (//) always rounds toward negative infinity. Therefore, -7 // 2 is -4, not -3.

###Q10. Why is NumPy Faster than Python Lists?

NumPy is faster because it is designed for efficient numerical computations.

1. Efficient Memory Storage:
NumPy arrays store data in a continuous block of memory, which allows faster access to elements. Python lists store references to objects, making them less efficient.
2. Same Data Type:
All elements in a NumPy array have the same data type. This eliminates the need for Python to check the type of each element during calculations.
3. Vectorized Operations:
NumPy performs operations using optimized C code behind the scenes. Instead of processing elements one by one in a Python loop, it operates on the entire array at once, making computations much faster.

Example:
```python
import numpy as np

arr = np.array([1, 2, 3, 4])
arr = arr * 2
```
- This multiplies all elements at once, whereas a Python list would typically require a loop. Therefore, NumPy is faster because of efficient memory usage, fixed data types, and optimized vectorized operations.

##Section B - Output Prediction

### Q11. List Multiplication vs List Comprehension
**a ) Predicted output**
```python
[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]
```



In [ ]:
# b )
matrix1 = [[0] * 3 for _ in range(3)]
matrix2 = [[0] * 3] * 3

matrix1[0][0] = 99
matrix2[0][0] = 99

print(matrix1)
print(matrix2)

[[99, 0, 0], [0, 0, 0], [0, 0, 0]]
[[99, 0, 0], [99, 0, 0], [99, 0, 0]]


**Why?**

matrix1 creates a new inner list for each row, so modifying one row affects only that row. matrix2 repeats the same inner list reference three times, so changing one row changes all rows because they point to the same list object.

### Q12. `x = x + [4]` vs `a += [4]`
**a ) Predicted outpu**t

```
x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]
```


In [ ]:
#b)
x = [1, 2, 3]
y = x
x = x + [4]
print("x =", x)
print("y =", y)

a = [1, 2, 3]
b = a
a += [4]
print("a =", a)
print("b =", b)

x = [1, 2, 3, 4]
y = [1, 2, 3]
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]


- **Now answer: Why do x = x + [4] and a += [4] behave differently?**

`x = x + [4]` creates a new list object and assigns it to `x`, leaving the original list unchanged. `a += [4]` modifies the existing list in place, so any other variable referencing that list (like `b`) also sees the change.

### Q13. Loop Variable After Loop
**a ) Predicted output**
```python
4
NameError: name 'j' is not defined
```
```
4
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_5537/4199568007.py in <cell line: 0>()
      4 for j in range(0):
      5  pass
----> 6 print(j) # think before you write

NameError: name 'j' is not defined
```


In [ ]:
for i in range(5):
 pass
print(i)
for j in range(0):
 pass
print(j) # think before you write

**Why**

The variable i exists after the loop and keeps its last assigned value (4). Since range(0) produces no values, the loop for j never runs, so j is never created, resulting in a NameError.

###Q14. Predict the output of each print statement. Then state which lines will raise an error (if any).
- Type Operations and Errors

**Predicted output:**
```
1020
30
101010
30
TypeError
30
```

In [ ]:
print("10" + "20")
print(10 + 20)
print("10" * 3)
print(10 * "3")
print("10" + 20)
print(int("10") + 20)

```
#My predicted and actual output doesn't match
```

In [ ]:
#Corrected code
print("10" + "20")
print(10 + 20)
print("10" * 3)
print(10 * "3")
try:
    print("10" + 20)
except TypeError as e:
    print(f"TypeError: {e}")
print(int("10") + 20)

**Explanation:**

- print`("10" + "20")` → Concatenates two strings → `1020`
print`(10 + 20)` → Adds two integers → `30`
- print`("10" * 3)` → Repeats `"10" `three times → 101010
- print`(10 * "3")` → Repeats` "3" `ten times → `3333333333`
- print`("10" + 20)` → Raises a TypeError, which is caught by the try-except block.
- print`(int("10") + 20)` → Converts `"10"` to an integer and adds 20 →`-  30`

### Q15. Short-Circuit Evaluation
- Predicted output:
```python
5
5
hello
0
10
default
[0]
```

In [ ]:
print(0 or 5)
print(5 or 0)
print(None or "hello")
print(0 and 5)
print(5 and 10)
print([] or "default")
print([0] or "default")  # careful!

5
5
hello
0
10
default
[0]


**Explanation**

- `0 or 5` → `5` because 0 is `False`, so or returns the second value.
- `5 or 0` →`5` because 5 is `True`, so or returns the first value.
- `None or "hello"` → `"hello"` because None is `False`.
- `0 and 5` → `0` because 0 is `False`, so and stops immediately.
- `5 and 10` → `10` because both values are `True`, so and returns the second value.
- `[] or "default"` →` "default" `because an empty list is` False`.
- `[0] or "default"` → `[0] `because a non-empty list is `True`.


Python stops evaluating an expression as soon as the final result is determined, avoiding unnecessary evaluation of the remaining operands.

###Section C - Coding Practice

C1 - Warm up

#### Q16. Swap Two Numbers — 3 Methods


In [ ]:
a = 10
b = 20

#arithmetic
a = a + b
b = a - b
a = a - b
print("Arithmetic:", a, b)

#xor (^)
a = a ^ b
b = a ^ b
a = a ^ b

print(f" XOR:",a, b)

#tuple
a = 10
b = 20

a, b = b, a

print("Tuple:",a, b)



Arithmetic: 20 10
 XOR: 10 20
Tuple: 20 10


###Q17. Swiggy Order Calculator

In [ ]:
price = float(input("Enter Item Price: "))
quantity = int(input("Enter Quantity: "))

subtotal = price * quantity
gst = subtotal * 0.18

if subtotal < 500:
    delivery = 40
else:
    delivery = 0

total = subtotal + gst + delivery

print("\nSubtotal:     ₹", format(subtotal, ".2f"))
print("GST (18%):    ₹", format(gst, ".2f"))
print("Delivery:     ₹", format(delivery, ".2f"))
print("------------------------")
print("Total:        ₹", format(total, ".2f"))


Enter Item Price: 200
Enter Quantity: 5

Subtotal:     ₹ 1000.00
GST (18%):    ₹ 180.00
Delivery:     ₹ 0.00
------------------------
Total:        ₹ 1180.00


###Q18. Temperature Converter

In [ ]:
temp = float(input("Enter Temperature: "))
unit = input("Enter Unit (C/F): ")

if unit == "C" or unit == "c":
    fahrenheit = (temp * 9/5) + 32
    print("Temperature in Fahrenheit:", round(fahrenheit, 2))

elif unit == "F" or unit == "f":
    celsius = (temp - 32) * 5/9
    print("Temperature in Celsius:", round(celsius, 2))

else:
    print("Error: Invalid unit! Try Again. Please enter C or F.")



Enter Temperature: 22
Enter Unit (C/F): c
Temperature in Fahrenheit: 71.6


###Q19. Sum of digits of a 4-digit number

In [ ]:
num = int(input("Enter a 4-digit number: "))

d1 = num // 1000
d2 = (num // 100) % 10
d3 = (num // 10) % 10
d4 = num % 10

sum = d1 + d2 + d3 + d4

print("Sum of digits =", sum)



Enter a 4-digit number: 1111
Sum of digits = 4


###Q20. Smart Input Parser

In [ ]:
value = input("Enter a value: ")

try:
    value = int(value)
    print("Value:", value)
    print("Type: int")

except:
    try:
        value = float(value)
        print("Value:", value)
        print("Type: float")

    except:
        print("Value:", value)
        print("Type: str")

Enter a value: 23
Value: 23
Type: int


###C2 – Conditionals & Logic

###Q21. Indian Income Tax Calculator

In [ ]:
income = float(input("Enter Annual Income: "))

tax = 0

if income <= 300000:
    tax = 0

elif income <= 700000:
    tax = (income - 300000) * 0.05

elif income <= 1000000:
    tax = (400000 * 0.05) + (income - 700000) * 0.10

elif income <= 1200000:
    tax = (400000 * 0.05) + (300000 * 0.10) + (income - 1000000) * 0.15

elif income <= 1500000:
    tax = (400000 * 0.05) + (300000 * 0.10) + (200000 * 0.15) + (income - 1200000) * 0.20

else:
    tax = (400000 * 0.05) + (300000 * 0.10) + (200000 * 0.15) + (300000 * 0.20) + (income - 1500000) * 0.30

print("\nTax Breakdown")
print("Up to ₹3,00,000      : ₹0.00")

if income > 300000:
    print("₹3,00,001 - ₹7,00,000  : ₹", min(income, 700000) - 300000, "taxed at 5%")

if income > 700000:
    print("₹7,00,001 - ₹10,00,000 : ₹", min(income, 1000000) - 700000, "taxed at 10%")

if income > 1000000:
    print("₹10,00,001 - ₹12,00,000: ₹", min(income, 1200000) - 1000000, "taxed at 15%")

if income > 1200000:
    print("₹12,00,001 - ₹15,00,000: ₹", min(income, 1500000) - 1200000, "taxed at 20%")

if income > 1500000:
    print("Above ₹15,00,000      : ₹", income - 1500000, "taxed at 30%")

print("---------------------------")
print("Total Tax = ₹", round(tax, 2))


Enter Annual Income: 2000000

Tax Breakdown
Up to ₹3,00,000      : ₹0.00
₹3,00,001 - ₹7,00,000  : ₹ 400000 taxed at 5%
₹7,00,001 - ₹10,00,000 : ₹ 300000 taxed at 10%
₹10,00,001 - ₹12,00,000: ₹ 200000 taxed at 15%
₹12,00,001 - ₹15,00,000: ₹ 300000 taxed at 20%
Above ₹15,00,000      : ₹ 500000.0 taxed at 30%
---------------------------
Total Tax = ₹ 290000.0


###Q22. Validate Indian PAN Card

In [ ]:
pan = input("Enter PAN number: ")

if len(pan) != 10:
    print("Invalid PAN - Length should be 10")

elif not pan[:5].isalpha() or not pan[:5].isupper():
    print("Invalid PAN - First 5 characters must be uppercase letters")

elif not pan[5:9].isdigit():
    print("Invalid PAN - Next 4 characters must be digits")

elif not pan[9].isalpha() or not pan[9].isupper():
    print("Invalid PAN - Last character must be an uppercase letter")

else:
    print("Valid PAN")


Enter PAN number: QWE5678
Invalid PAN - Length should be 10


###Q23. BESCOM Electricity Bill

In [ ]:
units = float(input("Enter Units Consumed: "))

if units <= 50:
    energy = units * 4.10

elif units <= 100:
    energy = (50 * 4.10) + ((units - 50) * 5.55)

elif units <= 200:
    energy = (50 * 4.10) + (50 * 5.55) + ((units - 100) * 7.10)

else:
    energy = (50 * 4.10) + (50 * 5.55) + (100 * 7.10) + ((units - 200) * 8.15)

fixed = 110
tax = (energy + fixed) * 0.06
total = energy + fixed + tax

print("\nElectricity Bill")
print("Energy Charges : ₹", round(energy, 2))
print("Fixed Charge   : ₹", fixed)
print("Govt Tax (6%)  : ₹", round(tax, 2))
print("-------------------------")
print("Total Bill     : ₹", round(total, 2))


Enter Units Consumed: 50

Electricity Bill
Energy Charges : ₹ 205.0
Fixed Charge   : ₹ 110
Govt Tax (6%)  : ₹ 18.9
-------------------------
Total Bill     : ₹ 333.9


###Q24. Cricket Strike Rate Classifier

In [ ]:
runs = int(input("Enter runs scored: "))
balls = int(input("Enter balls faced: "))

if balls == 0:
    print("Strike rate cannot be calculated (balls faced cannot be 0).")

else:
    sr = (runs / balls) * 100

    print("Strike Rate =", round(sr, 2))

    if sr > 150:
        print("Explosive (T20 finisher)")

    elif sr > 100:
        print("Aggressive (Top order T20)")

    elif sr >= 75:
        print("Steady (ODI anchor)")

    else:
        print("Defensive (Test match)")


Enter runs scored: 77
Enter balls faced: 24
Strike Rate = 320.83
Explosive (T20 finisher)


###Q25. BMI Calculator

In [ ]:
weight = float(input("Enter weight (kg): "))
height = float(input("Enter height (cm): "))

height = height / 100
bmi = weight / (height * height)

print("BMI =", round(bmi, 2))

if bmi < 18.5:
    print("Category: Underweight")

elif bmi <= 22.9:
    print("Category: Normal (Indian range)")

elif bmi <= 24.9:
    print("Category: Overweight")

elif bmi <= 29.9:
    print("Category: Obese Class I")

else:
    print("Category: Obese Class II")


Enter weight (kg): 40
Enter height (cm): 163
BMI = 15.06
Category: Underweight


###C3 	Nested Loop Patterns

###Q26. Print this pattern for N = 5: (Pattern Printing)

In [ ]:
n = int(input("Enter N: "))

for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

Enter N: 5
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


###Q27. Print this number diamond for N = 5 (the digits go up to N in the middle row): (Number Diamond)

In [ ]:
n = int(input("Enter N: "))

# Upper half
for i in range(1, n + 1):

    for j in range(n - i):
        print(" ", end="")

    for j in range(1, i + 1):
        print(j, end=" ")

    for j in range(i - 1, 0, -1):
        print(j, end=" ")

    print()

# Lower half
for i in range(n - 1, 0, -1):

    for j in range(n - i):
        print(" ", end="")

    for j in range(1, i + 1):
        print(j, end=" ")

    for j in range(i - 1, 0, -1):
        print(j, end=" ")

    print()

Enter N: 5
    1 
   1 2 1 
  1 2 3 2 1 
 1 2 3 4 3 2 1 
1 2 3 4 5 4 3 2 1 
 1 2 3 4 3 2 1 
  1 2 3 2 1 
   1 2 1 
    1 


###Q28. Print a hollow square of size N (only the border is *, inside is blank). For N = 5: (Hollow Square)

In [ ]:
n = int(input("Enter N: "))

for i in range(n):
    for j in range(n):

        if i == 0 or i == n - 1 or j == 0 or j == n - 1:
            print("*", end=" ")
        else:
            print(" ", end=" ")

    print()

Enter N: 7
* * * * * * * 
*           * 
*           * 
*           * 
*           * 
*           * 
* * * * * * * 


###Q29. Print the first 5 rows of Pascal's Triangle:
Pascal's Triangle (First N Rows)

In [ ]:
n = int(input("Enter number of rows: "))

for i in range(n):

    num = 1

    for j in range(n - i - 1):
        print(" ", end="")

    for j in range(i + 1):
        print(num, end=" ")
        num = num * (i - j) // (j + 1)

    print()


Enter number of rows: 8
       1 
      1 1 
     1 2 1 
    1 3 3 1 
   1 4 6 4 1 
  1 5 10 10 5 1 
 1 6 15 20 15 6 1 
1 7 21 35 35 21 7 1 


###Q30. Print this character pattern for N = 5 – letters go up to the N-th alphabet: (Character Pattern)

In [ ]:
n = int(input("Enter N: "))

for i in range(1, n + 1):
    for j in range(i):
        print(chr(ord('A') + j), end=" ")
    print()

Enter N: 9
A 
A B 
A B C 
A B C D 
A B C D E 
A B C D E F 
A B C D E F G 
A B C D E F G H 
A B C D E F G H I 


##C4 	Loop Logic

######Q31. Find all Armstrong numbers between 1 and 9999. (An n-digit number is Armstrong if the sum of its digits each raised to the power n equals the number itself. Example: 153 = 1³ + 5³ + 3³.) Print them in a clean comma-separated list with a count at the end.

In [ ]:
count = 0

for num in range(1, 10000):

    temp = num
    digits = 0

    while temp > 0:
        digits += 1
        temp = temp // 10

    temp = num
    total = 0

    while temp > 0:
        digit = temp % 10
        total = total + digit ** digits
        temp = temp // 10

    if total == num:
        print(num, end=", ")
        count += 1

print("\nTotal Armstrong Numbers =", count)

1, 2, 3, 4, 5, 6, 7, 8, 9, 153, 370, 371, 407, 1634, 8208, 9474, 
Total Armstrong Numbers = 16


######Q32. Take N as input. Print the first N terms of the Fibonacci series. Also compute and print the SUM of those N terms. Do NOT use recursion. Edge case: N = 0 should print nothing, sum = 0. N = 1 should print just 0.

In [ ]:
n = int(input("Enter N: "))

a = 0
b = 1
sum = 0

for i in range(n):
    print(a, end=" ")
    sum = sum + a

    c = a + b
    a = b
    b = c

print("\nSum =", sum)

Enter N: 6
0 1 1 2 3 5 
Sum = 12


######Q33. Prime check, optimized. Take a number N. Check if it is prime by iterating only up to √N. Then, print the SUM of all primes between 2 and N (inclusive). Do not use any library.

In [ ]:
n = int(input("Enter a number: "))

prime = True

if n < 2:
    prime = False

else:
    i = 2
    while i * i <= n:
        if n % i == 0:
            prime = False
            break
        i += 1

if prime:
    print(n, "is Prime")
else:
    print(n, "is Not Prime")

sum = 0

for num in range(2, n + 1):

    prime = True
    i = 2

    while i * i <= num:
        if num % i == 0:
            prime = False
            break
        i += 1

    if prime:
        sum = sum + num

print("Sum of Prime Numbers =", sum)

Enter a number: 12
12 is Not Prime
Sum of Prime Numbers = 28


######Q34. Take a number as input. Reverse it WITHOUT converting to string. Then check if the original and reversed are equal (palindrome). Handle negative numbers, they should be considered NOT palindrome (because of the minus sign). Examples: 121 → palindrome, 123 → not palindrome, -121 → not palindrome.

In [ ]:
num = int(input("Enter a number: "))

if num < 0:
    print("Not Palindrome")

else:
    original = num
    reverse = 0

    while num > 0:
        digit = num % 10
        reverse = reverse * 10 + digit
        num = num // 10

    print("Reversed Number =", reverse)

    if original == reverse:
        print("Palindrome")
    else:
        print("Not Palindrome")

Enter a number: 234
Reversed Number = 432
Not Palindrome


######Q35. Take two positive integers. Compute their HCF (Highest Common Factor) using Euclidean algorithm with a while loop. Then compute LCM using the relation: HCF × LCM = a × b. Do not use math.gcd.

In [ ]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

x = a
y = b

while y != 0:
    r = x % y
    x = y
    y = r

hcf = x
lcm = (a * b) // hcf

print("HCF =", hcf)
print("LCM =", lcm)

Enter first number: 56
Enter second number: 24
HCF = 8
LCM = 168


######Q36. String scanner, single pass. Take a sentence (e.g., a Swiggy review like "Order came on time, food was hot, packaging 10/10!"). In ONE pass through the string, count: total characters, total words, vowels (a, e, i, o, u - case-insensitive), consonants, digits, spaces, and special characters. Print all counts.

In [ ]:
text = input("Enter a sentence: ")

characters = 0
words = 1
vowels = 0
consonants = 0
digits = 0
spaces = 0
special = 0

for ch in text:

    characters += 1

    if ch == " ":
        spaces += 1
        words += 1

    elif ch.isdigit():
        digits += 1

    elif ch.isalpha():

        if ch.lower() in "aeiou":
            vowels += 1
        else:
            consonants += 1

    else:
        special += 1

print("Characters =", characters)
print("Words =", words)
print("Vowels =", vowels)
print("Consonants =", consonants)
print("Digits =", digits)
print("Spaces =", spaces)
print("Special Characters =", special)

Enter a sentence: The FIFA World 2026 is really amazing!
Characters = 38
Words = 7
Vowels = 10
Consonants = 17
Digits = 4
Spaces = 6
Special Characters = 1


##C5 	Lists, Tuples, Sets, Dicts

######Q37. Take 10 student marks (out of 100) as input, space-separated on one line, parse with split() and map(). Without using sort() or sorted(), find: (a) maximum, (b) minimum, (c) average, (d) count of students above average, (e) the SECOND highest mark.

In [ ]:
marks = list(map(int, input("Enter 10 marks: ").split()))

maximum = marks[0]
minimum = marks[0]
sum = 0

for i in marks:
    if i > maximum:
        maximum = i

    if i < minimum:
        minimum = i

    sum = sum + i

average = sum / len(marks)

count = 0
for i in marks:
    if i > average:
        count = count + 1

highest = marks[0]
second = marks[0]

for i in marks:
    if i > highest:
        second = highest
        highest = i
    elif i > second and i != highest:
        second = i

print("Maximum =", maximum)
print("Minimum =", minimum)
print("Average =", round(average, 2))
print("Students Above Average =", count)
print("Second Highest =", second)

Enter 10 marks: 23 23 56 78 90 98 78 77 60 70
Maximum = 98
Minimum = 23
Average = 65.3
Students Above Average = 6
Second Highest = 90


######Q38. Word Frequency Analyzer for Swiggy reviews. Take a review sentence. Find the frequency of each word (case-insensitive, "Food" and "food" should be counted together). Print words sorted by frequency in descending order. Also print the MOST frequent word and its count. Use a dict.

In [ ]:
review = input("Enter review: ")

review = review.lower()
words = review.split()

freq = {}

for word in words:
    if word in freq:
        freq[word] = freq[word] + 1
    else:
        freq[word] = 1

print("\nWord Frequencies:")

while len(freq) > 0:

    max_word = ""
    max_count = 0

    for word in freq:
        if freq[word] > max_count:
            max_count = freq[word]
            max_word = word

    print(max_word, ":", max_count)
    del freq[max_word]

Enter review: The tiramisu was well executed and incredibly delicious!

Word Frequencies:
the : 1
tiramisu : 1
was : 1
well : 1
executed : 1
and : 1
incredibly : 1
delicious! : 1


In [ ]:
#To print the most frequent word and count
max_word = ""
max_count = 0

for word in freq:
    if freq[word] > max_count:
        max_count = freq[word]
        max_word = word

print("Most Frequent Word =", max_word)
print("Count =", max_count)

Most Frequent Word = 
Count = 0


######Q39. Indian States CRUD. Pre-populate a dict with 5 Indian states and their capitals (e.g., Karnataka → Bengaluru, Maharashtra → Mumbai). Then build a menu-driven program: 1. Add a new state-capital pair 2. Update an existing capital 3. Delete a state 4. Search a state (return capital, or 'Not found') 5. Display all states sorted alphabetically 6. Exit Use a while loop. Loop until user chooses option 6.

In [ ]:
#Dictionary (dict)
#while loop
#if-elif-else
#input()
#print()

states = {
    "Karnataka": "Bengaluru",
    "Maharashtra": "Mumbai",
    "Gujarat": "Gandhinagar",
    "Tamil Nadu": "Chennai",
    "Kerala": "Thiruvananthapuram"
}

while True:

    print("\n----- MENU -----")
    print("1. Add State")
    print("2. Update Capital")
    print("3. Delete State")
    print("4. Search State")
    print("5. Display All States")
    print("6. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        state = input("Enter State Name: ")
        capital = input("Enter Capital: ")
        states[state] = capital
        print("State Added Successfully!")

    elif choice == 2:
        state = input("Enter State Name: ")

        if state in states:
            capital = input("Enter New Capital: ")
            states[state] = capital
            print("Capital Updated Successfully!")
        else:
            print("State Not Found!")

    elif choice == 3:
        state = input("Enter State Name: ")

        if state in states:
            del states[state]
            print("State Deleted Successfully!")
        else:
            print("State Not Found!")

    elif choice == 4:
        state = input("Enter State Name: ")

        if state in states:
            print("Capital =", states[state])
        else:
            print("Not Found")

    elif choice == 5:

        names = list(states.keys())

        # Bubble Sort
        for i in range(len(names)):
            for j in range(len(names) - i - 1):
                if names[j] > names[j + 1]:
                    temp = names[j]
                    names[j] = names[j + 1]
                    names[j + 1] = temp

        print("\nStates and Capitals:")
        for state in names:
            print(state, ":", states[state])

    elif choice == 6:
        print("Program Ended.")
        break

    else:
        print("Invalid Choice!")


----- MENU -----
1. Add State
2. Update Capital
3. Delete State
4. Search State
5. Display All States
6. Exit
Enter your choice: 1
Enter State Name: PUNJAB
Enter Capital: CHANDIGARH
State Added Successfully!

----- MENU -----
1. Add State
2. Update Capital
3. Delete State
4. Search State
5. Display All States
6. Exit
Enter your choice: 2
Enter State Name: MAHARASHTRA
State Not Found!

----- MENU -----
1. Add State
2. Update Capital
3. Delete State
4. Search State
5. Display All States
6. Exit
Enter your choice: 2
Enter State Name: MAHARASHTRA
State Not Found!

----- MENU -----
1. Add State
2. Update Capital
3. Delete State
4. Search State
5. Display All States
6. Exit
Enter your choice: 2
Enter State Name: Maharashtra
Enter New Capital: Mumbai
Capital Updated Successfully!

----- MENU -----
1. Add State
2. Update Capital
3. Delete State
4. Search State
5. Display All States
6. Exit
Enter your choice: 3
Enter State Name: Gujarat
State Deleted Successfully!

----- MENU -----
1. Add Stat

######Q40. Set Operations. Students in Section A know languages = {Python, Java, C++, SQL}. Students in Section B know = {Java, JavaScript, Python, Go, SQL}. Using ONLY set operations, find: (a) Languages known by BOTH sections (b) Languages known ONLY by Section A (c) Languages known ONLY by Section B (d) Total unique languages across both sections (e) Languages exclusive to one section but not both (symmetric difference)

In [ ]:
sectionA = {"Python", "Java", "C++", "SQL"}
sectionB = {"Java", "JavaScript", "Python", "Go", "SQL"}

#(a) Languages known by both sections
print("Both Sections:", sectionA & sectionB)

#(b) Languages known only by Section A
print("Only Section A:", sectionA - sectionB)

#(c) Languages known only by Section B
print("Only Section B:", sectionB - sectionA)

#(d) Total unique languages
print("All Unique Languages:", sectionA | sectionB)

#(e) Languages exclusive to one section
print("Symmetric Difference:", sectionA ^ sectionB)

Both Sections: {'Python', 'Java', 'SQL'}
Only Section A: {'C++'}
Only Section B: {'JavaScript', 'Go'}
All Unique Languages: {'Java', 'SQL', 'Python', 'Go', 'JavaScript', 'C++'}
Symmetric Difference: {'JavaScript', 'C++', 'Go'}


######Q41. TCS stock prices for a week stored as a tuple: prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055) (Mon to Sun in ₹). Find: (a) maximum price and which day, (b) minimum price and which day, (c) average, (d) biggest single-day gain (and between which days), (e) total volatility = sum of absolute day-to-day price changes.

In [ ]:
prices = (3845, 3902, 3878, 3955, 4012, 3998, 4055)
days = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

print("Maximum Price = ₹", max(prices), "on", days[prices.index(max(prices))])
print("Minimum Price = ₹", min(prices), "on", days[prices.index(min(prices))])

total = 0
for p in prices:
    total = total + p

average = total / len(prices)
print("Average Price = ₹", round(average, 2))

gain = prices[1] - prices[0]
day = days[0] + " to " + days[1]

for i in range(1, len(prices)):
    if prices[i] - prices[i-1] > gain:
        gain = prices[i] - prices[i-1]
        day = days[i-1] + " to " + days[i]

print("Biggest Gain = ₹", gain, "from", day)

volatility = 0
for i in range(1, len(prices)):
    volatility = volatility + abs(prices[i] - prices[i-1])

print("Total Volatility = ₹", volatility)

Maximum Price = ₹ 4055 on Sun
Minimum Price = ₹ 3845 on Mon
Average Price = ₹ 3949.29
Biggest Gain = ₹ 77 from Wed to Thu
Total Volatility = ₹ 286


######Q42. Given a list of 20 integers (you generate or hardcode them, some duplicates), produce: (a) the set of unique numbers, (b) the list of numbers appearing more than once, (c) the list of numbers appearing EXACTLY once. Do this WITHOUT importing Counter or any other library.

In [ ]:
numbers = [5, 8, 2, 5, 9, 3, 8, 1, 6, 7,
           2, 4, 10, 6, 11, 12, 13, 11, 14, 15]

unique = set(numbers)

duplicate = []
once = []

for i in unique:
    count = 0

    for j in numbers:
        if i == j:
            count = count + 1

    if count > 1:
        duplicate.append(i)

    if count == 1:
        once.append(i)

print("Unique Numbers:", unique)
print("Duplicate Numbers:", duplicate)
print("Appearing Exactly Once:", once)

Unique Numbers: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
Duplicate Numbers: [2, 5, 6, 8, 11]
Appearing Exactly Once: [1, 3, 4, 7, 9, 10, 12, 13, 14, 15]


##C6 Strings

######Q43. Smart Palindrome Checker. Take a sentence as input. Check if it is a palindrome IGNORING: case, spaces, and all special characters (punctuation). Examples that should return TRUE: "A man, a plan, a canal: Panama", "Race car", "No 'x' in Nixon". Hint: build a cleaned version of the string first.

In [ ]:
text = input("Enter a sentence: ")

clean = ""

for ch in text:
    if ch.isalnum():
        clean = clean + ch.lower()

if clean == clean[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")

Enter a sentence: Race car
Palindrome


######Q44. Manual Title Case. Take a sentence (e.g., "hello world from bengaluru"). Capitalize the first letter of EACH word, but do NOT use .title() or .capitalize(). Use only .upper() / .lower() and string indexing. Output: "Hello World From Bengaluru".

In [ ]:
text = input("Enter a sentence: ")

result = ""
new_word = True

for ch in text:

    if ch == " ":
        result = result + ch
        new_word = True

    else:
        if new_word:
            result = result + ch.upper()
            new_word = False
        else:
            result = result + ch.lower()

print("Title Case:", result)

Enter a sentence: hello world from bengaluru
Title Case: Hello World From Bengaluru


######Q45. Caesar Cipher Encryptor. Take a message and a shift value N as input. Encrypt by shifting each letter forward by N positions in the alphabet (wrapping around, Z + 1 = A). Preserve case. Keep digits, spaces, and special characters UNCHANGED. Example: "Hello, India!" with shift 3 → "Khoor, Lqgld!"

In [ ]:
text = input("Enter message: ")
shift = int(input("Enter shift value: "))

result = ""

for ch in text:

    if ch.isupper():
        new = ord(ch) + shift

        if new > ord('Z'):
            new = new - 26

        result = result + chr(new)

    elif ch.islower():
        new = ord(ch) + shift

        if new > ord('z'):
            new = new - 26

        result = result + chr(new)

    else:
        result = result + ch

print("Encrypted Message:", result)

Enter message: hello, india
Enter shift value: 3
Encrypted Message: khoor, lqgld


##C7 - Functions

######Q46. Write a function `calculate_gst(amount, gst_rate=18, gst_inclusive=False)`:

In [ ]:
def calculate_gst(amount, gst_rate=18, gst_inclusive=False):

    if gst_inclusive == False:
        base = amount
        gst = base * gst_rate / 100
        total = base + gst

    else:
        total = amount
        base = total * 100 / (100 + gst_rate)
        gst = total - base

    return round(base, 2), round(gst, 2), round(total, 2)


print(calculate_gst(1000))
print(calculate_gst(1180, gst_inclusive=True))
print(calculate_gst(500, gst_rate=5))

(1000, 180.0, 1180.0)
(1000.0, 180.0, 1180)
(500, 25.0, 525.0)


######Q47. Write a RECURSIVE function `power(base, exp)` that computes base raised to exp, WITHOUT using the `**` operator and WITHOUT using `pow()`. Handle exp = 0 (return 1) and negative exp (return 1/power(base, -exp)). Test with: power(2, 10), power(5, 0), power(3, -2).

In [ ]:
def power(base, exp):

    if exp == 0:
        return 1

    elif exp < 0:
        return 1 / power(base, -exp)

    else:
        return base * power(base, exp - 1)


print(power(2, 10))
print(power(5, 0))
print(power(3, -2))

1024
1
0.1111111111111111


##C8 NumPy Foundations

######Q48. Identity Matrix Manipulations. Using NumPy: (a) create a 5×5 identity matrix using np.eye(), (b) multiply every element by 10, (c) transpose it (yes, it looks the same, explain in a comment WHY transpose of an identity is itself), (d) compute the sum of diagonal elements, (e) compute the sum of all elements. Print each step.

In [ ]:
import numpy as np

a = np.eye(5)

print("Identity Matrix:")
print(a)

b = a * 10

print("\nAfter Multiplying by 10:")
print(b)

c = b.T

# Transpose of an identity matrix is the same because
# all diagonal elements remain in the same positions.
print("\nTranspose:")
print(c)

print("\nSum of Diagonal =", np.trace(c))

print("Sum of All Elements =", np.sum(c))

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

After Multiplying by 10:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Transpose:
[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]

Sum of Diagonal = 50.0
Sum of All Elements = 50.0


######Q49. Zomato Weekly Sales Analytics. Create a NumPy array of 7-day Zomato Bengaluru sales (in ₹):
```PYTHON
sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])
             # Mon    Tue    Wed    Thu    Fri    Sat    Sun
```
```PYTHON
Without using loops, compute and print:
(a)	Total weekly sales
(b)	Daily average
(c)	The day (Mon/Tue/...) with maximum sales
(d)	Number of days with sales above the weekly average
(e)	Percentage growth from Monday to Sunday
(f)	An array of day-on-day % changes (length 6)
```

In [ ]:
import numpy as np

sales = np.array([12000, 18500, 14200, 22100, 19800, 35200, 28400])

days = np.array(["Mon","Tue","Wed","Thu","Fri","Sat","Sun"])

print("Total Sales =", np.sum(sales))

print("Average Sales =", np.mean(sales))

print("Maximum Sales Day =", days[np.argmax(sales)])

print("Days Above Average =", np.sum(sales > np.mean(sales)))

growth = ((sales[-1] - sales[0]) / sales[0]) * 100
print("Growth from Monday to Sunday =", round(growth,2), "%")

change = ((sales[1:] - sales[:-1]) / sales[:-1]) * 100
print("Day-to-Day % Changes:")
print(np.round(change,2))

Total Sales = 150200
Average Sales = 21457.14285714286
Maximum Sales Day = Sat
Days Above Average = 3
Growth from Monday to Sunday = 136.67 %
Day-to-Day % Changes:
[ 54.17 -23.24  55.63 -10.41  77.78 -19.32]


######Q50. The Border Pattern Challenge – NO explicit loops. Create a 5×5 NumPy array where the BORDER is 1 and the INTERIOR is 0. Output should look like:
```
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
 ```
Constraint: You may use np.ones(), np.zeros(), and slicing, but NO `for`, NO `while`, NO list comprehension. Only NumPy operations.

In [ ]:
import numpy as np

a = np.ones((5,5), dtype=int)

a[1:4,1:4] = 0

print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
